require( "love.filesystem" )
require( "src/helper" )
Tserial = require( "src/tserial" )
Class = require( "src/30log" )
Vector = require( "src/vector" )
Camera = require( "src/camera" )
Entity = require( "src/entity" )
Entities = require( "src/entities" )
World = require( "src/world" )
Render = require( "src/render" )
-- Options = require( "src/options" )
GameState = require( "src/gamestate" )
PackLoader = require( "src/packloader" ):init()
Server = require( "src/network/server" )

function love.load()
    love.math.setRandomSeed( love.timer.getTime() )
    Server:start( "*", "27020" )
    GameState.registerEvents()
    GameState.switch( require( PackLoader:getRequire( "gamestates/server/lobby" ) ) )
end
